apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgCmO+GFCqp5p+HwE8K681gOw1Dm+SdbCILhV5DN4eUBcq+9le5a+55DPeXw/yy0BSwOykFs6bDwmt0+8H0NyRgGqWCMw59j2CPhSTECvcEmVavWb0+NjLTiaDXSbNykBqldtsDUhqaP6mlNWFDQytOqtc+KE11hDPeDkcMjLSlQ9XsNsIhnclOXVE1D/nvzJYQI++6QFUBKJcYagrB5yK5y9DTUH/QVfxthnPLF36Cb+uLtCOmhY07PL3erosNnKD776wIA4JHJsd4LMPGcfrZRKBHBaoIEgbz0EIk8GJAL2p1iXyoSx+I9npT1qZ1G2iToqa9ZoLnD1aCDO8aWnwlJY74eSlUY58m4t/62glgNLL4rT/z0mm8qPRuYsunp6bcK8JO6Nk/juYqgtgMqGGwieaTvogwTIA/1aTcjSc7ToOBHheV0UMkegVZsQ+sw29SuPKhdIO5Jih1j6n89Jws/VA7OafOTiWfw7AMaGVsuIN7ASNifw2grFIf20Tpc/e/RVgoGt51Aw/u2MboJ8InhwBgA5qOpctUgnJC4nZxP6Dzu/OoU2L53elcZQQm7ouegPFM2PPaMX8xkDwaDAdHvy+FzT6nWXIX25OrS1KBE8smdu5w4SeQXLqkM6ZBXXlnZwUuEHuN3TQdBcZcRCH46/hNi/7i9Cfy7XS0f1W+UHHBF+BRmB2skaC3bxHqysYpS+OPbef8LLsfwjncUtXhXuad4NOIPkAmkfw4/CNNehLIsuUB89ZIitD/tvIt3fPoD+UEKRxyPOIeCJ7V0HLvxKNcdu3bN9BoqEaMFO46lcdejm0NuGzXYC1m8CPcWtxTEQ3tYxSMBq+9lrROt9FZnnkPXt7PJrRRJey/PuTSAjeKh5rHBS30EV9fc7hKipTD4tZxzY2VH
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

